export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SHOW_LOADING = 'SHOW_LOADING';